services:
  goa-support:
    build: .
    image: goa-support:latest
    restart: always
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/goasupportdb
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
      SPRING_SECURITY_OAUTH2_JWK-URI: http://host.docker.internal:8080/api/goa-user/oauth2/jwks
      SPRING_SECURITY_OAUTH2_TOKEN-URI: http://host.docker.internal:8080/api/goa-user/oauth2/token
    networks:
      - goa
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  goa:
    external: true

#> docker compose up --build -d
#> docker compose up --build -d --scale goa-support=2

# Para ver los logs de arranque
#> docker logs -f goa-support