spring:
  security:
    oauth2:
      jwk-uri: ${HOST}/api/goa-user/oauth2/jwks
      token-uri: ${HOST}/api/goa-user/oauth2/token
      api-client-id: ${API_CLIENT_ID}
      api-client-secret: ${API_CLIENT_SECRET}
  mail:
    password: ${MAIL_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://goa-eureka:8761/eureka/

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
