logging:
  level:
    root: WARN
    es.upm.api: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${BASE_URL}/api/goa-user/oauth2/jwks
  mail:
    password: ${MAIL_PASSWORD}

app:
  oauth2:
    token-uri: ${BASE_URL}/api/goa-user/oauth2/token
    api-client-id: ${API_CLIENT_ID}
    api-client-secret: ${API_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://goa-eureka:8761/eureka/

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
